target("mymodGui")
    add_rules("qt.widgetapp")
	add_rules("ue4ss.mod")
    add_headerfiles("*.h")
    add_files("*.cpp")
	add_files("*.c")
	add_files("mymodGui.ui")
	add_files("mymodGui.h")
